PUBLIC_HEADERS:=public_headers.$(PROFILE)

.PHONY: all
all:: all-$(COMPONENT_PART)

include $(MAKEFILES_COMMON_BASE_DIR)/lib_app_common.mk

#
# ALL
#
.PHONY: all-MKPUBLIC
all-MKPUBLIC:: $(PUBLIC_HEADERS)
.PHONY: all-OBJECTS
all-OBJECTS:: $(LIBRARY_OBJ_DEPS)
.PHONY: all-LINK
all-LINK:: $(LIBRARY_NAME)
